2024-04-28 15:28:35,507 INFO    StreamThr :25130 [internal.py:wandb_internal():86] W&B internal server running at pid: 25130, started at: 2024-04-28 15:28:35.504534
2024-04-28 15:28:35,507 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status
2024-04-28 15:28:35,509 INFO    WriterThread:25130 [datastore.py:open_for_write():87] open: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/run-hk1o0sn4.wandb
2024-04-28 15:28:35,521 DEBUG   SenderThread:25130 [sender.py:send():379] send: header
2024-04-28 15:28:35,521 DEBUG   SenderThread:25130 [sender.py:send():379] send: run
2024-04-28 15:28:36,042 INFO    SenderThread:25130 [dir_watcher.py:__init__():211] watching files in: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files
2024-04-28 15:28:36,042 INFO    SenderThread:25130 [sender.py:_start_run_threads():1124] run started: hk1o0sn4 with start time 1714310915.504329
2024-04-28 15:28:36,083 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: check_version
2024-04-28 15:28:36,084 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: check_version
2024-04-28 15:28:36,168 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: run_start
2024-04-28 15:28:36,169 DEBUG   HandlerThread:25130 [system_info.py:__init__():26] System info init
2024-04-28 15:28:36,170 DEBUG   HandlerThread:25130 [system_info.py:__init__():41] System info init done
2024-04-28 15:28:36,170 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:28:36,170 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:28:36,171 INFO    HandlerThread:25130 [system_monitor.py:probe():214] Collecting system info
2024-04-28 15:28:36,171 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:28:36,171 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:28:36,173 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:28:36,173 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:28:36,174 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:28:36,196 DEBUG   HandlerThread:25130 [system_info.py:probe():150] Probing system
2024-04-28 15:28:36,196 DEBUG   HandlerThread:25130 [gitlib.py:_init_repo():56] git repository is invalid
2024-04-28 15:28:36,197 DEBUG   HandlerThread:25130 [system_info.py:probe():198] Probing system done
2024-04-28 15:28:36,197 DEBUG   HandlerThread:25130 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-105-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-04-28T13:28:36.196262', 'startedAt': '2024-04-28T13:28:35.454192', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'host': 'clab20', 'username': 'pederu', 'executable': '/bin/python', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3717.1060833333336, 'min': 3000.0, 'max': 4700.0}, 'cpu_freq_per_core': [{'current': 5364.635, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 5225.87, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 4700.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 4700.0, 'min': 3000.0, 'max': 4700.0}, {'current': 4700.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 4875.971, 'min': 3000.0, 'max': 4700.0}, {'current': 4700.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3720.041, 'min': 3000.0, 'max': 4700.0}, {'current': 4700.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 4700.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}, {'current': 3000.0, 'min': 3000.0, 'max': 4700.0}], 'disk': {'/': {'total': 97.87200164794922, 'used': 49.07643127441406}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 61.94272994995117}}
2024-04-28 15:28:36,197 INFO    HandlerThread:25130 [system_monitor.py:probe():224] Finished collecting system info
2024-04-28 15:28:36,197 INFO    HandlerThread:25130 [system_monitor.py:probe():227] Publishing system info
2024-04-28 15:28:36,201 INFO    HandlerThread:25130 [system_monitor.py:probe():229] Finished publishing system info
2024-04-28 15:28:36,202 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:28:36,202 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-04-28 15:28:36,625 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: python_packages
2024-04-28 15:28:36,626 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: python_packages
2024-04-28 15:28:36,666 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:28:36,666 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:28:36,666 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:28:36,890 INFO    wandb-upload_0:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/zzj309j6-wandb-metadata.json
2024-04-28 15:28:36,918 DEBUG   SenderThread:25130 [sender.py:send():379] send: telemetry
2024-04-28 15:28:37,047 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:28:37,047 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/requirements.txt
2024-04-28 15:28:37,049 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/wandb-metadata.json
2024-04-28 15:28:39,050 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:28:41,023 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:28:43,060 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:28:45,063 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:28:46,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:28:51,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:28:51,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:28:51,628 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:28:51,792 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:28:56,793 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:01,793 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:06,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:29:06,626 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:29:06,670 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:29:06,820 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:07,102 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/config.yaml
2024-04-28 15:29:12,005 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:17,005 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:21,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:29:21,626 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:29:21,670 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:29:22,819 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:25,167 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:26,168 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:27,866 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:28,171 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:30,172 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:32,174 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:32,901 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:34,175 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:36,174 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:29:36,174 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:29:36,177 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:36,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:29:36,627 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:29:36,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:29:38,011 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:38,178 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:38,256 DEBUG   SenderThread:25130 [sender.py:send():379] send: telemetry
2024-04-28 15:29:38,257 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:38,257 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:40,179 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:43,729 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:43,925 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:45,423 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:45,423 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:45,486 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:29:45,486 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/labels_1_d4bb7d4d1dd59b46c264.jpg with policy now
2024-04-28 15:29:45,486 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:45,554 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:29:45,554 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:45,554 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/train_batch0_1_5c6c35b492cac58d6fa6.jpg with policy now
2024-04-28 15:29:45,697 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:29:45,697 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/train_batch1_1_674b3c081b229e9c81f5.jpg with policy now
2024-04-28 15:29:45,697 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:45,837 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:45,837 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:29:45,840 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/train_batch2_1_13c9b6cfe25be8ffcecd.jpg with policy now
2024-04-28 15:29:45,867 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:29:46,300 INFO    wandb-upload_0:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/dabm4rsa-media/images/labels_1_d4bb7d4d1dd59b46c264.jpg
2024-04-28 15:29:46,426 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/train_batch1_1_674b3c081b229e9c81f5.jpg
2024-04-28 15:29:46,427 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/train_batch2_1_13c9b6cfe25be8ffcecd.jpg
2024-04-28 15:29:46,427 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/labels_1_d4bb7d4d1dd59b46c264.jpg
2024-04-28 15:29:46,428 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/train_batch0_1_5c6c35b492cac58d6fa6.jpg
2024-04-28 15:29:46,428 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images
2024-04-28 15:29:46,428 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media
2024-04-28 15:29:46,797 INFO    wandb-upload_1:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/yng0pai7-media/images/train_batch0_1_5c6c35b492cac58d6fa6.jpg
2024-04-28 15:29:46,878 INFO    wandb-upload_2:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/svs90wya-media/images/train_batch1_1_674b3c081b229e9c81f5.jpg
2024-04-28 15:29:46,941 INFO    wandb-upload_3:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/ctokxzls-media/images/train_batch2_1_13c9b6cfe25be8ffcecd.jpg
2024-04-28 15:29:47,132 INFO    wandb-upload_0:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/sewcztrw-media/images/labels_1_d4bb7d4d1dd59b46c264.jpg
2024-04-28 15:29:47,936 INFO    wandb-upload_1:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/nci8p1mu-media/images/train_batch0_1_5c6c35b492cac58d6fa6.jpg
2024-04-28 15:29:48,237 INFO    wandb-upload_3:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/8th71o8b-media/images/train_batch1_1_674b3c081b229e9c81f5.jpg
2024-04-28 15:29:48,431 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:48,917 INFO    wandb-upload_0:25130 [upload_job.py:push():131] Uploaded file /tmp/tmpdllwgo3wwandb/cqxi0pg2-media/images/train_batch2_1_13c9b6cfe25be8ffcecd.jpg
2024-04-28 15:29:48,988 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:50,436 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:51,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:29:51,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:29:51,627 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:29:52,440 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:54,263 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:29:54,443 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:56,448 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:58,451 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:29:59,492 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:00,455 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:01,799 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:01,800 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:01,800 DEBUG   SenderThread:25130 [sender.py:send():379] send: history
2024-04-28 15:30:01,800 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: summary_record
2024-04-28 15:30:01,803 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-28 15:30:02,460 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:02,460 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/wandb-summary.json
2024-04-28 15:30:04,463 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:05,004 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:06,175 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:30:06,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:30:06,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:30:06,627 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:30:07,053 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:08,698 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:10,246 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:10,788 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/config.yaml
2024-04-28 15:30:10,789 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:11,791 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:13,801 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:15,604 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:15,807 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:17,814 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:19,820 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:20,846 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:21,626 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:30:21,627 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:30:21,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:30:21,825 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:23,833 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:24,844 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:24,844 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:24,844 DEBUG   SenderThread:25130 [sender.py:send():379] send: history
2024-04-28 15:30:24,846 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: summary_record
2024-04-28 15:30:24,857 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-28 15:30:25,838 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:25,839 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/wandb-summary.json
2024-04-28 15:30:25,860 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:29,281 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:30,887 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:32,529 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:33,531 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:34,535 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:35,539 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:36,110 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:36,175 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:30:36,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:30:36,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:30:36,629 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:30:37,548 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:39,555 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:41,267 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:41,561 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:43,567 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:45,575 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:45,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:45,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:30:45,627 DEBUG   SenderThread:25130 [sender.py:send():379] send: history
2024-04-28 15:30:45,629 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: summary_record
2024-04-28 15:30:45,636 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-04-28 15:30:46,276 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:46,623 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/wandb-summary.json
2024-04-28 15:30:47,627 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:51,485 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:30:51,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:30:51,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:30:51,628 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:30:52,859 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:30:56,236 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:30:56,236 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:30:56,236 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:30:56,236 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:30:56,236 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:30:56,236 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:30:56,237 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:30:56,294 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:30:56,294 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:30:56,297 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:30:56,297 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:30:57,297 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:02,298 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:06,627 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:31:06,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:31:06,629 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:31:07,828 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:12,828 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:17,829 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:21,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:31:21,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:31:21,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:31:22,837 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:27,837 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:32,838 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:36,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:31:36,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:31:36,628 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:31:37,891 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:42,892 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:47,893 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:51,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:31:51,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:31:51,629 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:31:53,822 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:31:58,822 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:00,879 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:32:00,879 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:32:00,879 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:32:00,879 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:32:00,879 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:32:00,879 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:32:00,880 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:32:00,880 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:32:00,881 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:32:00,922 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:32:00,922 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:32:00,922 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:32:00,922 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:32:00,922 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:32:00,939 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:32:00,939 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:32:00,939 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:32:00,973 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:32:00,973 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:32:00,977 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:32:00,978 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:32:01,139 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:32:03,444 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:32:04,141 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:06,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:32:06,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:32:06,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:32:09,881 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:13,051 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:32:15,052 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:15,466 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:32:20,052 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:21,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:32:21,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:32:21,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:32:25,065 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:32:25,065 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:27,502 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:32:30,066 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:35,066 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:36,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:32:36,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:32:36,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:32:37,078 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:32:39,565 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:32:40,078 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:45,079 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:49,105 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:32:50,106 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:32:51,611 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:32:51,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:32:51,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:32:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:32:55,885 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:00,886 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:01,096 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:33:03,657 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:33:06,097 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:06,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:33:06,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:33:06,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:33:11,780 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:13,105 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:33:15,709 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:33:17,106 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:21,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:33:21,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:33:21,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:33:22,783 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:25,125 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:33:27,737 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:33:28,126 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:33,127 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:36,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:33:36,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:33:36,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:33:38,808 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:43,809 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:48,809 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:51,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:33:51,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:33:51,629 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:33:53,861 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:33:58,862 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:01,645 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:01,645 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:01,645 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:01,646 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:01,646 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:01,646 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:01,646 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:01,647 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:01,648 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:01,690 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:01,690 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:01,690 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:01,690 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:01,691 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:01,690 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:01,691 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:01,691 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:01,737 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:01,737 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:01,738 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:01,738 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:01,884 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:34:03,796 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:34:03,885 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:05,577 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:05,578 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:05,578 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:05,578 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:05,578 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:05,578 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:05,579 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:05,579 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:05,579 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:05,581 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:05,582 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:05,582 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:05,583 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:05,583 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:05,583 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:05,583 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:05,583 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:05,626 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:05,626 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:05,627 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:05,630 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:06,209 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:06,209 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:06,209 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:06,209 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:06,209 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:06,209 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:06,210 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:06,210 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:06,210 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:06,211 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:06,212 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:06,212 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:06,212 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:06,212 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:06,212 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:06,213 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:06,213 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:06,245 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:06,245 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:06,246 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:06,247 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:06,438 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:06,438 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:06,438 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:06,439 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:06,439 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:06,439 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:06,439 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:06,440 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:06,440 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:06,442 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:06,443 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:06,443 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:06,443 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:06,443 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:06,443 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:06,443 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:06,443 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:06,488 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:06,488 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:06,488 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:06,490 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:06,628 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:34:06,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:34:06,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:34:07,746 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:07,746 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:07,746 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:07,746 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:07,746 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:07,746 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:07,747 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:07,747 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:07,747 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:07,786 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:07,786 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:07,786 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:07,786 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:07,786 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:07,787 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:07,787 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:07,787 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:07,821 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:07,821 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:07,821 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:07,824 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:07,824 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:07,824 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:07,824 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:07,824 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:07,824 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:07,824 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:07,824 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:07,826 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:07,826 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:07,826 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:07,826 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:07,827 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:07,827 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:09,289 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:09,289 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:09,289 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:09,289 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:09,290 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:09,290 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:09,290 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:09,291 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:09,291 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:09,293 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:09,293 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:09,293 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:09,293 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:09,293 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:09,293 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:09,294 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:09,295 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:09,331 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:09,331 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:09,333 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:09,333 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:09,334 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:10,121 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:10,121 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:10,121 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:10,122 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:10,122 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:10,122 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:10,122 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:34:10,122 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:34:10,123 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:34:10,123 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:10,125 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:10,125 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:10,125 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:10,125 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:10,125 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:10,126 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:10,126 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:10,161 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:34:10,161 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:34:10,162 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:34:10,163 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:34:10,163 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:34:10,163 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:10,163 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:34:10,163 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:34:10,163 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:34:10,163 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:34:10,163 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:34:10,163 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:34:10,165 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:34:10,165 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:34:10,165 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:34:10,165 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:34:10,166 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:34:10,166 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:34:10,166 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:34:15,167 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:20,168 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:21,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:34:21,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:34:21,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:34:25,901 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:30,901 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:35,902 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:36,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:34:36,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:34:36,629 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:34:40,325 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:34:41,326 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:41,977 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:34:46,326 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:51,327 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:34:51,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:34:51,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:34:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:34:56,855 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:01,856 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:06,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:35:06,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:35:06,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:35:07,823 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:11,199 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:35:13,123 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:35:13,200 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:18,201 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:21,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:35:21,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:35:21,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:35:23,800 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:28,801 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:33,801 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:36,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:35:36,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:35:36,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:35:38,890 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:43,225 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:35:44,225 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:45,192 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:35:49,226 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:51,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:35:51,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:35:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:35:54,880 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:35:59,880 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:04,881 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:06,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:36:06,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:36:06,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:36:10,837 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:15,265 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:36:16,265 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:17,284 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:36:21,266 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:21,629 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:36:21,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:36:21,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:36:26,785 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:31,785 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:36,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:36:36,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:36:36,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:36:36,882 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:41,883 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:46,884 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:47,312 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:36:49,505 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:36:51,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:36:51,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:36:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:36:51,894 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:36:56,894 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:01,895 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:06,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:37:06,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:37:06,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:37:07,822 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:12,823 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:17,823 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:19,319 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:37:21,619 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:37:21,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:37:21,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:37:21,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:37:22,862 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:27,863 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:32,863 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:36,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:37:36,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:37:36,630 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:37:38,839 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:43,840 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:48,840 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:51,351 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:37:51,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:37:51,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:37:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:37:53,672 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:37:54,826 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:37:59,826 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:04,827 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:06,630 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:38:06,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:38:06,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:38:09,860 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:14,860 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:19,861 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:21,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:38:21,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:38:21,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:38:23,381 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:38:25,381 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:25,818 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:38:30,382 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:35,382 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:36,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:38:36,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:38:36,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:38:40,883 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:45,884 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:50,885 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:51,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:38:51,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:38:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:38:55,416 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:38:56,417 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:38:58,059 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:39:01,418 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:06,418 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:06,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:39:06,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:39:06,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:39:11,811 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:16,812 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:21,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:39:21,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:39:21,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:39:21,881 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:26,881 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:27,442 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:39:30,123 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:39:32,444 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:36,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:39:36,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:39:36,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:39:37,806 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:42,806 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:47,807 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:51,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:39:51,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:39:51,631 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:39:52,808 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:57,808 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:39:59,462 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:40:02,211 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:40:03,463 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:06,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:40:06,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:40:06,633 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:40:08,891 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:13,892 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:18,892 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:21,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:40:21,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:40:21,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:40:24,892 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:29,893 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:31,490 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:40:34,332 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:40:35,491 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:36,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:40:36,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:40:36,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:40:40,815 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:45,815 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:50,816 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:40:51,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:40:51,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:40:51,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:40:55,889 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:00,889 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:03,519 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:41:05,436 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:06,520 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:06,631 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:41:06,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:41:06,633 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:41:11,882 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:16,883 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:21,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:41:21,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:41:21,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:41:22,880 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:27,881 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:32,881 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:35,546 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:41:36,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:41:36,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:41:36,632 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:41:37,497 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:37,882 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:42,883 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:42,955 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: resume
2024-04-28 15:41:42,955 INFO    HandlerThread:25130 [handler.py:handle_request_resume():699] starting system metrics thread
2024-04-28 15:41:42,955 INFO    HandlerThread:25130 [system_monitor.py:start():194] Starting system monitor
2024-04-28 15:41:42,956 INFO    SystemMonitor:25130 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-28 15:41:42,956 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started cpu monitoring
2024-04-28 15:41:42,956 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started disk monitoring
2024-04-28 15:41:42,957 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started gpu monitoring
2024-04-28 15:41:42,957 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started memory monitoring
2024-04-28 15:41:42,957 INFO    SystemMonitor:25130 [interfaces.py:start():190] Started network monitoring
2024-04-28 15:41:44,545 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:47,560 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:48,600 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:48,873 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:49,605 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:50,609 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:51,613 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:51,638 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:41:51,639 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:41:51,639 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:41:52,617 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:53,621 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:53,952 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:55,630 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:57,636 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:41:58,985 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:41:59,647 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:01,660 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:03,670 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:04,378 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:05,605 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:42:05,678 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:05,751 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:42:06,310 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:06,310 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:06,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:42:06,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:42:06,635 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:42:07,684 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:09,694 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:09,930 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:15,388 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:19,392 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:19,394 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:19,488 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:42:19,488 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:19,489 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/labels_4_d4bb7d4d1dd59b46c264.jpg with policy now
2024-04-28 15:42:19,608 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:19,608 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:42:19,608 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/train_batch0_4_5c6c35b492cac58d6fa6.jpg with policy now
2024-04-28 15:42:19,658 ERROR   wandb-upload_1:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:19,658 ERROR   wandb-upload_1:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:19,658 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/50q9t15m-media/images/labels_4_d4bb7d4d1dd59b46c264.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:19,753 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:42:19,753 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:19,946 ERROR   wandb-upload_3:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:19,971 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/train_batch1_4_674b3c081b229e9c81f5.jpg with policy now
2024-04-28 15:42:19,973 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:19,973 ERROR   wandb-upload_3:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:19,974 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:19,974 DEBUG   SenderThread:25130 [sender.py:send():379] send: files
2024-04-28 15:42:19,974 INFO    SenderThread:25130 [sender.py:_save_file():1390] saving file media/images/train_batch2_4_13c9b6cfe25be8ffcecd.jpg with policy now
2024-04-28 15:42:19,974 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/uqyopwli-media/images/train_batch0_4_5c6c35b492cac58d6fa6.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:20,175 ERROR   wandb-upload_2:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:20,175 ERROR   wandb-upload_2:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:20,175 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/z9xc8zla-media/images/train_batch1_4_674b3c081b229e9c81f5.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:20,222 ERROR   wandb-upload_1:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:20,478 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:24,038 ERROR   wandb-upload_1:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:24,038 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-28 15:42:24,038 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:42:24,039 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/v5rus11q-media/images/train_batch2_4_13c9b6cfe25be8ffcecd.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:24,039 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:42:24,615 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:24,615 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/labels_4_d4bb7d4d1dd59b46c264.jpg
2024-04-28 15:42:24,617 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/train_batch1_4_674b3c081b229e9c81f5.jpg
2024-04-28 15:42:24,617 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/train_batch0_4_5c6c35b492cac58d6fa6.jpg
2024-04-28 15:42:24,618 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_created():271] file/dir created: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images/train_batch2_4_13c9b6cfe25be8ffcecd.jpg
2024-04-28 15:42:24,618 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/media/images
2024-04-28 15:42:24,835 ERROR   wandb-upload_0:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:24,835 ERROR   wandb-upload_0:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:24,835 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/c8qsd1u7-media/images/labels_4_d4bb7d4d1dd59b46c264.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:24,868 ERROR   wandb-upload_2:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:24,868 ERROR   wandb-upload_2:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:24,868 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/i40v3vqw-media/images/train_batch1_4_674b3c081b229e9c81f5.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:25,017 ERROR   wandb-upload_3:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:25,017 ERROR   wandb-upload_3:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:25,017 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/x99zxhle-media/images/train_batch0_4_5c6c35b492cac58d6fa6.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:25,069 ERROR   wandb-upload_1:25130 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-28 15:42:25,069 ERROR   wandb-upload_1:25130 [internal_api.py:execute():374] {"errors":[{"message":"run YOLOv8/hk1o0sn4 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-04-28 15:42:25,069 ERROR   Thread-80 (_thread_body):25130 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdllwgo3wwandb/i446guus-media/images/train_batch2_4_13c9b6cfe25be8ffcecd.jpg
Traceback (most recent call last):
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/pederu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/filesync/upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2386, in upload_urls
    query_result = self.gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/pederu/.local/lib/python3.10/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-28 15:42:25,485 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:25,622 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:27,632 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:29,642 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:30,642 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:31,653 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:33,665 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:35,646 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:42:35,647 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:35,674 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:35,798 ERROR   FileStreamThread:25130 [file_stream.py:_handle_response():523] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/pederu00/YOLOv8/hk1o0sn4/file_stream
NoneType: None
2024-04-28 15:42:36,117 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:36,117 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: partial_history
2024-04-28 15:42:36,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: keepalive
2024-04-28 15:42:36,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:42:36,634 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:42:37,680 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:39,686 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:40,434 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: pause
2024-04-28 15:42:40,434 INFO    HandlerThread:25130 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-04-28 15:42:40,434 INFO    HandlerThread:25130 [system_monitor.py:finish():203] Stopping system monitor
2024-04-28 15:42:40,434 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-28 15:42:40,435 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-28 15:42:40,435 DEBUG   SystemMonitor:25130 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-28 15:42:40,435 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined cpu monitor
2024-04-28 15:42:40,436 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined disk monitor
2024-04-28 15:42:40,500 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined gpu monitor
2024-04-28 15:42:40,501 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined memory monitor
2024-04-28 15:42:40,502 INFO    HandlerThread:25130 [interfaces.py:finish():202] Joined network monitor
2024-04-28 15:42:40,502 DEBUG   SenderThread:25130 [sender.py:send():379] send: stats
2024-04-28 15:42:40,690 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:41,503 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:41,694 INFO    Thread-81 :25130 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/pederu/Documents/YOLOv8_project/wandb/run-20240428_152835-hk1o0sn4/files/output.log
2024-04-28 15:42:46,503 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:51,504 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:42:51,632 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: keepalive
2024-04-28 15:42:51,633 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: stop_status
2024-04-28 15:42:51,635 DEBUG   SenderThread:25130 [sender.py:send_request():406] send_request: stop_status
2024-04-28 15:42:56,806 DEBUG   HandlerThread:25130 [handler.py:handle_request():146] handle_request: status_report
2024-04-28 15:43:00,286 INFO    MainThread:25130 [internal.py:handle_exit():76] Internal process exited
2024-04-28 15:43:00,286 INFO    MainThread:25130 [internal.py:handle_exit():76] Internal process exited
2024-04-28 15:43:00,286 INFO    MainThread:25130 [internal.py:handle_exit():76] Internal process exited
2024-04-28 15:43:00,286 INFO    MainThread:25130 [internal.py:handle_exit():76] Internal process exited
2024-04-28 15:43:00,286 INFO    MainThread:25130 [internal.py:handle_exit():76] Internal process exited
